
import { FieldDefinition } from './types';

export const FIELD_LABELS: string[] = [
  "Número do Processo",
  "Nome do Solicitante",
  "Telefone do Solicitante",
  "E-mail do Solicitante",
  "Executiva",
  "Setor do Solicitante",
  "Caso o Setor for Outros, Informe Aqui",
  "Programa",
  "Nome do Evento",
  "Período do Evento",
  "Horário do Evento",
  "Data de Saída",
  "Data do Retorno",
  "Horário de Saída",
  "Horário de Retorno",
  "Cidade de Origem",
  "Local de Saída",
  "Endereço Completo de Origem",
  "PARADA 1",
  "PARADA 2",
  "PARADA 3",
  "PARADA 4",
  "PARADA 5",
  "PARADA 6",
  "Cidade de Destino",
  "Local de Destino",
  "Endereço Completo de Destino",
  "Total de Passageiros",
  "Modalidade da Viagem",
  "Disponibilidade de Veículo",
  "Nome do Responsável",
  "Telefone do Responsável",
  "Informações Complementares"
];

export const EXECUTIVA_OPTIONS = [
  "GABSEE - Gabinete da Secretária",
  "SAD - Secretaria de Administração de Pernambuco",
  "SEAF - Secretaria Executiva de Administração e Finanças",
  "SEAM - Secretaria Executiva de Planejamento e Coordenação",
  "SEAP - Secretaria de Administração Penitenciária e Ressocialização",
  "SEDE - Secretaria Executiva de Desenvolvimento da Educação",
  "SEES - Secretaria Executiva de Esportes",
  "SEGE - Secretaria Executiva de Gestão da Rede",
  "SEGP - Secretaria Executiva de Gestão de Pessoas",
  "SEMP - Secretaria Executiva de Educação Integral e Profissional",
  "SEOB - Secretaria Executiva de Obras"
];

export const SETOR_OPTIONS = [
  "AAFG - Assessoria Administrativa Financeira",
  "AJGGPE - Gerência Geral de Gestão de Pessoas",
  "AJUG - Assessoria Juridica Gabinete",
  "ASTEC - Assessoria Técnica",
  "BPE - UADM - Unidade Administrativa Biblioteca Pública de Pernambuco",
  "CAC - Coord de Ações Culturais",
  "CAGP - Coordenação Administrativa de Gestão de Pessoas",
  "CALF - Coordenação de Alfabetização de Jovens e Adultos",
  "CBR - Coordenação de Base e Rendimento",
  "CCEFP - Coordenação de Cadastro e Elaboração de Folha de Pagamento",
  "CEAI - Coordenação dos Anos Iniciais do Ensino Fundamental",
  "CECEB - Coordenação do Censo Escolar da Educação Básica",
  "CECF - Coordenação de Correção de Fluxo",
  "CEEI - Coordenação Estadual de Educação Infantil",
  "CGAF-MN - Coordenação geral de Administração e Finanças",
  "CGAM-VC - Coordenação Geral de Articulação Municipal - CGAM - VC Limoeiro",
  "CGDE-GRE AM - Coordenação Geral de Desenvolvimento da Educação - CGDE - AM Garanhuns",
  "CGDE-MC - Coordenação Geral de Desenvolvimento da Educação - CGDE - MC Vitória",
  "CGEMP-MS - Coordenação Geral do Ensino Médio e Profissional - MS",
  "CGEMP-RS - Coordenação Geral de Ensino Médio e Profissional",
  "CGEMP-SAP - Coordenação Geral do Ensino Médio e Profissional - CGEMP - SAP Afogados da Ingazeira",
  "CGEMP-SMI - Coordenação geral de Ensino Médio e Profissional - SMI Arcoverde",
  "CGPP - Coordenação Geral de Programas e Projetos da Rede",
  "CNP - Coordenação de Novos Projetos",
  "COEFP - Coordenação de Obrigações e Encargos de Folha de Pagamento",
  "CORREGED - Corregedoria",
  "CPL I - Comissão Permanente de Licitação I",
  "CPL III - Comissão Permanente de Licitação III",
  "CPL IV - Comissão Permanente de Licitação IV",
  "CPM - Conservatório Pernambucano de Música",
  "CPPU - Coordenação do Programa Projovem Urbano",
  "CTG - Coordenação Técnica de Gestão",
  "CTNE - Coordenação Técnica de Normatização e Supervisão do Sistema Estadual de Educação",
  "CTPETE - Coordenação do Programa Estadual de Transporte Escolar",
  "FUNDEF - Fundo de Manutenção e Desenvolvimento do Ensino Fundamental e de Valorização do Magistério",
  "GABSEDE - Gabinete da Secretaria Executiva de Desenvolvimento da Educação",
  "GACE - Gestão de Acompanhamento à Execução de Contratos de Engenharia",
  "GAM - Gerência de Articulação Municipal",
  "GAPE - Gerência de Arquitetura e Orçamento",
  "GAPRO - Gerência Técnica de Acompanhamento Programático",
  "GATG - Gerência de Apoio Técnica ao Gabinete",
  "GCES - Gerência Técnica de Centros Esportivos",
  "GCINC - Gerência de Controle Interno e Correição",
  "GCODA - Gerência Técnica Jurídica de Contratação Direta e Adesões",
  "GCOMP - Gerência de Compras",
  "GCRE - Gestão De Contratos da Rede Escolar",
  "GDEP - Gerência de Desenvolvimento de Pessoas",
  "GEAME - Gerência de Análise de Mercado",
  "GEARE - Gerência Administrativa da Rede Escolar",
  "GECAP - Gerência de Captação de Recursos",
  "GECON - Gerência Contábil",
  "GEDES - Gerência de Execução da Despesa",
  "GEDH - Gerência de Politicas Educagionais e Cidadania",
  "GEEQ - Gerência de Educação Escolar Quilombola (Antiga CEEQ)",
  "GEFP - Gerência de Gestão Financeira de Pessoal",
  "GEINT - Gerência Técnica de Intercâmbio",
  "GEJAI - Gerência de Políticas Educacionais de Jovens, Adultos e Idosos",
  "GELIC - Gerência Técnica Jurídica de Licitações e Contratos",
  "GELOG - Gerência de Logística",
  "GEMAP - Gerência de Movimentação e Acompanhamento de Pessoal",
  "GEMR - Gerência de Manutenção da Rede",
  "GENSE - Gerência de Normatização e Supervisão do Sistema Estadual de Educação",
  "GEOE - Gestão de Organização da Rede Escolar",
  "GEPAF - Gerência de Políticas Educacionais dos Anos Finais Fundamental",
  "GEPCC - Gerência de Prestação de Contas de Convênio",
  "GEPEC - Gerência de Políticas Educacionais do Campo",
  "GEPEM - Gerência de Políticas Educacionais do Ensino Médio",
  "GEPFI - Gerência Técnica de Programação Financeira",
  "GEPLA/ APLAN - Gerência de Planejamento, Monitoramento e Avaliação",
  "GEPLO - Gerência de Planejamento Orçamentário",
  "GEPPE - Gestão de Planejamento e Projetos Especiais",
  "GERED - Gerência Técnica de Educação à Distância",
  "GERET - Gerência Técnica das Escolas Técnicas",
  "GERJI - Gerência Técnica de Jornada Integral",
  "GERJS - Gerência Técnica de Jornada Semi-Integral",
  "GERPE - Gestão De Programas e Projetos Especiais",
  "GESAD - Gerência de Serviços Administrativos",
  "GETAF - Gerência Técnica Administrativa Financeira",
  "GETAN - Gerência Técnica de Alimentação e Nutrição",
  "GETRA - Gerência de Transportes",
  "GGADM - Gerência Geral de Administração",
  "GGAE - Gerência Geral de Arquitetura e Engenharia",
  "GGAJ - Gerência Geral de Assuntos Jurídicos",
  "GGCP - Gerência Geral de Coordenação de Programas e Projetos Prioritários",
  "GGDIP - Gerência Geral de Desenvolvimento Pedagógico, Inovação e Projetos Especiais (Antiga SUPEFI)",
  "GGEAF - Gerência Geral Do Ensino Médio e Anos Finais Do Ensino Fundamental",
  "GGEI - Gerência Geral de Educação Integral",
  "GGEP - Gerência Geral de Educação Profissional",
  "GGES - Gerência Geral de Esportes",
  "GGFIC - Superintendência de Execução Orçamentária e Financeira",
  "GGFR - Gerência Geral Financeira Da Rede Escolar",
  "GGGR - Gerência Geral de gestão da Rede Escolar",
  "GGMOD - Gerência Geral Das Modalidades",
  "GGPE - Gerência Geral de Gestão de Pessoas",
  "GGTIC - Gerência Geral de Tecnologia da Informação",
  "GISA - Gerência de Informações e Sistemas Aplicativos",
  "GITI - Gerência de Infraestrutura e Tecnologia de Informação",
  "GJAF - Gerência Técnica Jurídica, Administrativa e Financeira",
  "GJUCE - Gerência Técnica Jurídica de Contratações de Engenharia",
  "GMRE - Gestão de Monitoramento da Rede Escolar",
  "GPCON - Gerência de Prestação de Contas",
  "GPIE - Gerência Técnica de Programas de Incentivo ao Esporte",
  "GRE-ACN - Gabinete da GRE Agreste Centro Norte - ACN -Caruaru",
  "GPLAN - Gerência Técnica de Planejamento Estratégico",
  "GRE-RS - Gabinete da GRE RECIFE SUL - RS",
  "GRI - Gerência de Relações Institucionais",
  "GRIMP - Gerência Técnica de Relações com a Imprensa",
  "GSTE - Gerência de Suporte Técnico",
  "GTCLI - Gerência Técnica de Cursos de Línguas e Pós Intercâmbio",
  "GTCON - Gerência Técnica de Contratos",
  "GTLIC - Gerência Técnica de Licitação",
  "GTPAT - Gerência Técnica de Patrimônio",
  "GTPP - Gerência Técnica de Programas e Projetos Prioritários",
  "GTRES - Gestão Técnica da Rede Escolar",
  "NAS - Núcleo de Atenção ao Servidor",
  "NASE - Núcleo de Análise de Solicitação de Empenho",
  "NGAPRO - Núcleo da Gerência Técnica de Acompanhamento Programático",
  "NUSAD - Núcleo de Serviços Administrativos",
  "OUTROS",
  "OUV - Ouvidoria",
  "PAAF - Coordenação de Projetos de Ampliação da Aprendizagem",
  "SAJES - Superintendência de Assuntos Jurídicos Especializados",
  "SAJUR - Superintendência de Assuntos Jurídicos de Contratações",
  "SCOMP - Superintendência de Compras",
  "SEAP - GAB - SEAP - GABINETE DO SECRETÁRIO",
  "SUASE - Superintendência de Atenção ao Servidor e Relações do Trabalho",
  "SUCE - Superintendência de Centros Esportivos",
  "SUCOM - Superintendência de Comunicação",
  "SUCOP - Superintendência de Convênios e Captação de Recursos",
  "SUCOSP - Gerência de Cessão e Seleção de Pessoal",
  "SUEAI - Superintendência De Educação Infantil E Anos Iniciais Do Ensino Fundamental",
  "SUES - Superintendência de Esportes",
  "SULIC - Superintendência de Licitações e Contratos",
  "SULOG - Superintendência de Logística e Serviços Administrativos",
  "SUOBR - Superintendência de Obras da Rede",
  "SUPAE - Superintendência do Programa de Alimentação Escolar",
  "SUPED - Superintendência Pedagógica",
  "SUPGM - Superintendência do Programa Ganhe o Mundo",
  "SUPI - Superintendência de Programas de Incentivo",
  "SUPIN - Superintendência de Política Educacional Indígena",
  "SUPOF - Superintendência de Planejamento Orçamentário e Financeiro",
  "UAB - Coordenação dos Polos Presenciais do Sistema Universidade Aberta do Brasil",
  "UABP - Unidade de Análise de Benefícios Previdenciários",
  "UAGC - Unidade de Assessoramento à Gestão da Carreira Profissional",
  "UAGP - Unidade Administrativa de Gestão de Pessoas",
  "UAN - Unidade de Atos Normativos",
  "UATA - Unidade de Apoio Técnico Administrativo",
  "UATF - Unidade de Atendimento Funcional",
  "UBEN - Unidade de Benefícios ao Servidor",
  "UCES - Unidade de Cessão de Servidores",
  "UEBLL - Unidade de Ensino, Bibliotecas, Leituras e Linguagens",
  "UECE - Unidade de Emissão de Certidões",
  "UEFAF - Unidade dos Anos Finais do Ensino Fundamental",
  "UEJAI - Unidade de Educação de Jovens, Adultos e Idosos",
  "UELAP - Unidade de Exonerações, Licenças e Afastamentos de Pessoal",
  "UEST - Unidade de Estágio",
  "UFGC - Unidade de Formação e Gestão do Conhecimento",
  "UMCT - Unidade de Monitoramento de contratos temporarios",
  "UMOP I - Unidade de Movimentação de Pessoal das Áreas I",
  "UMOP II - Unidade de Movimentação de Pessoal das Áreas II",
  "UNAPC - Unidade de Acompanhamento do Programa PE NO CAMPUS",
  "UNAPE - Unidade de Acompanhamento de Projetos Especiais",
  "UNEDI - Unidade de Educação Inclusiva",
  "UNIEC - Unidade de Políticas Educacionais do Campo",
  "UNIEI - Unidade de Educação Escolar Indígena",
  "UNIEM - Unidade de Ensino Médio",
  "UNPAT - Unidade de Patrimônio",
  "UNPEL - Unidade do Projeto Escola Legal",
  "UNPPAG - Unidade de Processamento de Pagamento de Despesas",
  "UNVALID - Unidade de Validação Documental de Despesas",
  "UPCON - Unidade de Prestação de Contas",
  "UPCP - Unidade de Prestação de Contas de Pessoal",
  "UPGP I - Unidade de Pagamento de Pessoal das Áreas I",
  "UPGP II - Unidade de Pagamento de Pessoal das Áreas II",
  "USEP - Unidade de Seleção de Pessoas",
  "USGE - Unidade de Serviços Gerais (Protocolo)"
];

export const PROGRAMA_OPTIONS = [
  "BANDAS E FANFARRAS", "BOA VISÃO", "CLIPE", "CONSERVATÓRIO", "GANHE O MUNDO", 
  "GRES", "PROFESP", "SEDE", "SEGE", "SEMP", "VISITA ESCOLAR", "OUTROS"
];

export const MODALIDADE_OPTIONS = [
  "APENAS IDA", "APENAS VOLTA", "IDA + VOLTA"
];

export const DISPONIBILIDADE_OPTIONS = [
  "RETORNO PROGRAMADO", "DISPONÍVEL NO LOCAL"
];

export const FIELDS: FieldDefinition[] = FIELD_LABELS.map((label, index) => {
  let type: FieldDefinition['type'] = 'text';
  
  if (label.includes('Data')) type = 'date';
  if (label.includes('Horário')) type = 'time';
  if (label.includes('Telefone')) type = 'tel';
  if (label.includes('E-mail')) type = 'email';
  if (label.includes('Total')) type = 'number';

  return {
    id: `col_${index}`,
    label: label,
    placeholder: ``,
    type: type,
    // Deixa obrigatório todos os campos exceto:
    // 3: E-mail, 4: Executiva, 5: Setor, 6: Outros, 12: Data Retorno, 14: Hora Retorno, 18-23: Paradas, 32: Complementares
    required: ![3, 4, 5, 6, 12, 14, 18, 19, 20, 21, 22, 23, 32].includes(index)
  };
});
